[package]
name = "eris"
version = "1.2.1"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2018"
description = "Liquid staking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://www.erisprotocol.com"
repository = "https://github.com/erisprotocol/contracts-kujira"

[dependencies]
cosmwasm-std = "1.1.3"
cosmwasm-schema = "1.1.3"
cw20 = "0.13.2"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
kujira = "0.7.13"

